### ISSUE TITLE
Should we be able to configure sv_fps 30 on servers?

### ISSUE THREAD

**Issue by xyeLz** [promod/promod4#1]
Sorry - I know it's been a long while since anyone has asked a question, but I'm working on a server config and in the config file is `set sv_fps 30`. However, in the actual server when I login with the rcon and perform `/rcon sv_fps` the output is 20.

Just making sure I'm not missing something here.

**Comment by Ingramz** [comment]
Hi, sorry for not noticing your question earlier.

Promod currently forces `sv_fps` to 20 [here](https://github.com/promod/promod4/blob/d22de10be2625674f252be29448530220db48228/promod/servercheck.gsc#L24).
The reason for this is simple - we don't know what are the side effects of values different from 20. Currently some scripts will not wait as long if `sv_fps` is set higher, which we can fix by simply adjusting the wait statements (this needs to be also done in script files used by Promod but do not come with Promod - the _stock_ scripts shipped with CoD4) by a known factor.  Dangers of doing this can be for instance rounding errors due to multiplying with weird numbers - timings can go wrong by a fraction. If anyone wants to try fixing the timings and include the necessary files, pull requests are always welcome, however until all side effects are known, this will be considered an experimental feature.

I've talked about adjusting these values with a CoD4X developer and what I heard was that it won't do what you think it does - player movement and associated hit registration are based off some parameters that are different from server FPS. I cannot remember the details as that was some time ago, but the overall suggestion was to not mess with it.

**Comment by kristiandz** [comment]
Tested promod on different sv_fps settings, can confirm it wont affect hitreg etc.
Suggest to close the issue as its not worth changing it, too many unexcepted errors can occur.
